name: nginx-dev
services:
  nginx:
    container_name: nginx
    image: nginx:1.26-alpine-perl
    volumes:
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/conf/conf.d/:/etc/nginx/conf.d/:ro
      - ./data/nginx/html/:/usr/share/nginx/html/:ro
    ports:
      - "80:80"